/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'link', label: 'Documentation Home', href: '/'},
	{
		type: 'category',
		label: 'OpenMetal Central',
		items: [
			{type: 'autogenerated', dirName: 'openmetal-central'},
		],
	},
	{
		type: 'category',
		label: 'Engineer\'s Notes',
		items: [
			{type: 'autogenerated', dirName: 'engineers-notes'},
		],
	},
	{
		type: 'html',
		value: '<li class="om-sidebar-category"><strong>Bare Metal</strong></li>',
	},
	{type: 'autogenerated', dirName: 'baremetal'},
	{
		type: 'html',
		value: '<li class="om-sidebar-category"><strong>OpenStack</strong></li>',
	},
	{
		type: 'category',
		label: 'Operator\'s Manual',
		link: {type: 'doc', id: 'operators-manual/index'},
		items: [
			{type: 'autogenerated', dirName: 'operators-manual'},
		],
	},
	{
	 	type: 'category',
	 	label: 'User\'s Manuals',
		link: {type: 'doc', id: 'users-manual/index'},
	 	items: [
			{type: 'autogenerated', dirName: 'users-manual'},
		],
	},
	{
	 	type: 'category',
	 	label: 'Tutorials',
		link: {type: 'doc', id: 'tutorials/index'},
	 	items: [
			{type: 'autogenerated', dirName: 'tutorials'},
		],
	},
	{
		type: 'category',
		label: 'Kubernetes',
		link: {type: 'doc', id: 'kubernetes-guides/index'},
	 	items: [
			{
				type: 'autogenerated',
				dirName: 'kubernetes-guides',
			},
		],
	},
  ],
};

module.exports = sidebars;
