/**
 * Operators Manual sidebar configuration with autogenerated content
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsOperators = {
  operatorsSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Operator\'s Manual',
      link: {type: 'doc', id: 'index'},
      items: [
        {type: 'autogenerated', dirName: '.'},
      ],
    },
  ],
};

module.exports = sidebarsOperators;