/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'link', label: 'Documentation Home', href: '/' },
    {
      type: 'category',
      label: 'OpenMetal Central',
      items: [{ type: 'autogenerated', dirName: 'openmetal-central' }],
    },
    {
      type: 'category',
      label: "Engineer's Notes",
      items: [{ type: 'autogenerated', dirName: 'engineers-notes' }],
    },
    {
      type: 'html',
      value: '<strong>Bare Metal</strong>',
      className: 'om-sidebar-category',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{ type: 'autogenerated', dirName: 'baremetal/tutorials' }],
    },
    {
      type: 'html',
      value: '<strong>OpenStack</strong>',
      className: 'om-sidebar-category',
    },
    {
      type: 'link',
      label: "Operator's Manual",
      href: '/operators-manual',
    },
    {
      type: 'doc',
      label: 'Kolla Image Updates',
      id: 'kolla-image-update/build-history',
    },
    {
      type: 'doc',
      label: "User's Manuals",
      id: 'users-manual/index',
    },
    {
      type: 'doc',
      label: 'Tutorials',
      id: 'tutorials/index',
    },
    {
      type: 'doc',
      label: 'Kubernetes',
      id: 'kubernetes-guides/index',
    },
    {
      type: 'doc',
      label: 'Private AI',
      id: 'private-ai/engineering-notes/index',
    },
  ],
  centralSidebar: [],
  engineersNotesSidebar: [],
  baremetalTutorialsSidebar: [],
  kollaImageUpdateSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Kolla Image Updates',
      link: { type: 'doc', id: 'kolla-image-update/build-history' },
      items: [{ type: 'autogenerated', dirName: 'kolla-image-update' }],
    },
  ],
  usersManualSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: "User's Manuals",
      link: { type: 'doc', id: 'users-manual/index' },
      items: [{ type: 'autogenerated', dirName: 'users-manual' }],
    },
  ],
  openstackTutorialsSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'tutorials/index' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
  ],
  kubernetesGuidesSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Kubernetes',
      link: { type: 'doc', id: 'kubernetes-guides/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'kubernetes-guides',
        },
      ],
    },
  ],
  privateAiEngineeringNotesSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Private AI',
      link: { type: 'doc', id: 'private-ai/engineering-notes/index' },
      items: [
        { type: 'autogenerated', dirName: 'private-ai/engineering-notes' },
      ],
    },
  ],
};

module.exports = sidebars;
