/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'link', label: 'Documentation Home', href: '/' },
    {
      type: 'html',
      defaultStyle: true,
      className: 'om-sidebar-html-link',
      value:
        '<a class="menu__link om-sidebar-external" href="/docs/manuals/api/" target="_blank" rel="noopener noreferrer">API Reference<svg class="om-sidebar-external__icon" viewBox="0 0 512 512" aria-hidden="true" focusable="false"><path fill="currentColor" d="M320 0c-17.7 0-32 14.3-32 32s14.3 32 32 32h82.7L201.4 265.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L448 109.3V192c0 17.7 14.3 32 32 32s32-14.3 32-32V32c0-17.7-14.3-32-32-32H320zM80 32C35.8 32 0 67.8 0 112V432c0 44.2 35.8 80 80 80H400c44.2 0 80-35.8 80-80V320c0-17.7-14.3-32-32-32s-32 14.3-32 32V432c0 8.8-7.2 16-16 16H80c-8.8 0-16-7.2-16-16V112c0-8.8 7.2-16 16-16H192c17.7 0 32-14.3 32-32s-14.3-32-32-32H80z"/></svg><span class="sr-only">(opens in a new tab)</span></a>',
    },
    {
      type: 'category',
      label: 'OpenMetal Central',
      items: [{ type: 'autogenerated', dirName: 'openmetal-central' }],
    },
    {
      type: 'html',
      value: '<strong>Bare Metal</strong>',
      className: 'om-sidebar-category',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{ type: 'autogenerated', dirName: 'baremetal/tutorials' }],
    },
    {
      type: 'html',
      value: '<strong>Ceph</strong>',
      className: 'om-sidebar-category',
    },
    {
      type: 'category',
      label: 'S3',
      //link: {type: 'doc', id: 's3/index'},
      items: [
        { type: 'autogenerated', dirName: 's3' },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      //link: {type: 'doc', id: 'troubleshooting/index'},
      items: [
        { type: 'autogenerated', dirName: 'troubleshooting' },
      ],
    },
    {
      type: 'html',
      value: '<strong>OpenStack</strong>',
      className: 'om-sidebar-category',
    },
    {
      type: 'link',
      label: "Operator's Manual",
      href: '/operators-manual',
    },
    {
      type: 'category',
      label: 'Compute',
      //link: {type: 'doc', id: 'compute/index'},
      items: [
        {type: 'autogenerated', dirName: 'compute'},
      ],
    },
    {
      type: 'category',
      label: 'Network',
      //link: {type: 'doc', id: 'compute/index'},
      items: [
        {type: 'autogenerated', dirName: 'network'},
      ],
    },
    {
      type: 'category',
      label: 'Image Service',
      //link: {type: 'doc', id: 'compute/index'},
      items: [
        {type: 'autogenerated', dirName: 'image'},
      ],
    },
    {
      type: 'category',
      label: 'VPNaaS',
      //link: {type: 'doc', id: 'vpnaas/index'},
      items: [
        {type: 'autogenerated', dirName: 'vpnaas'},
      ],
    },
    {
      type: 'doc',
      label: 'Kolla Image Updates',
      id: 'kolla-image-update/build-history',
    },
    {
      type: 'doc',
      label: "User's Manuals",
      id: 'users-manual/index',
    },
    {
      type: 'doc',
      label: 'Kubernetes',
      id: 'kubernetes-guides/index',
    },
    {
      type: 'doc',
      label: 'Private AI',
      id: 'private-ai/engineering-notes/index',
    },
  ],
  centralSidebar: [],
  engineersNotesSidebar: [],
  baremetalTutorialsSidebar: [],
  kollaImageUpdateSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Kolla Image Updates',
      link: { type: 'doc', id: 'kolla-image-update/build-history' },
      items: [{ type: 'autogenerated', dirName: 'kolla-image-update' }],
    },
  ],
  usersManualSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: "User's Manuals",
      link: { type: 'doc', id: 'users-manual/index' },
      items: [{ type: 'autogenerated', dirName: 'users-manual' }],
    },
  ],
  kubernetesGuidesSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Kubernetes',
      link: { type: 'doc', id: 'kubernetes-guides/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'kubernetes-guides',
        },
      ],
    },
  ],
  privateAiEngineeringNotesSidebar: [
    {
      type: 'link',
      label: '← Return To Home',
      href: '/',
      className: 'back-to-home-link',
    },
    {
      type: 'category',
      label: 'Private AI',
      link: { type: 'doc', id: 'private-ai/engineering-notes/index' },
      items: [
        { type: 'autogenerated', dirName: 'private-ai/engineering-notes' },
      ],
    },
  ],
};

module.exports = sidebars;
